info:
  title: DirectSQL REST API
  version: '1.0'
openapi: 3.0.3
paths:
  /miscforeign-keys:
    get:
      description: Return current settings
      operationId: GetPragmaDirectives
      parameters: []
      responses:
        '200':
          content:
            application/json: {}
            text/csv: {}
            text/tsv: {}
          description: 200 OK
      summary: Get Pragma Directives
  /v1/lists:
    post:
      description: The list is automatically shared with the owner
      operationId: CreateANewList(todo)
      parameters: []
      responses:
        '200':
          content:
            application/json: {}
            text/csv: {}
            text/tsv: {}
          description: 200 OK
      summary: Create a new list (TODO)
  /v1/sessions:
    delete:
      description: 'Revoke a session.


        Authentication: User Password'
      operationId: DeleteASession
      parameters: []
      responses:
        '200':
          content:
            application/json: {}
            text/csv: {}
            text/tsv: {}
          description: 200 OK
      summary: Delete a session
    get:
      description: 'Return all (active) sessions.


        Authentication: Session token.'
      operationId: GetSessions
      parameters: []
      responses:
        '200':
          content:
            application/json: {}
            text/csv: {}
            text/tsv: {}
          description: 200 OK
      summary: Get sessions
    post:
      description: 'Authenticate the user with their password to generate a token.


        A token is used to authenticate with the remainder of the API.


        This allows sessions to continue even when a password changes, and allows
        individual sessions to be revoked.'
      operationId: CreateANewSession
      parameters: []
      responses:
        '200':
          content:
            application/json: {}
            text/csv: {}
            text/tsv: {}
          description: 200 OK
      summary: Create a new Session
  /v1/users:
    post:
      description: Create a new User, returning the User ID
      operationId: CreateANewUser
      parameters: []
      responses:
        '200':
          content:
            application/json: {}
            text/csv: {}
            text/tsv: {}
          description: 200 OK
      summary: Create a new User
